apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.20.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: master
  name: master
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.20.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: master
    spec:
      containers:
      - env:
        - name: MASTER_ADDR
          value: master
        - name: PYTORCH_PORT
          value: "29501"
        - name: PYTORCH_SOCKET
          value: eth0
        - name: RANK
          value: "0"
        image: jet
        name: master
        resources: {}
      restartPolicy: Always
status: {}
